### ISSUE TITLE
Record support

### ISSUE THREAD

**Issue by DomasM** [k94ll13nn3/AutoConstructor#64]
Hi, would you consider supporting record types too? I played around a bit, there seems to be pretty much single line difference between class and record generation, so it seems I have a working solution.
[My branch is here](https://github.com/DomasM/AutoConstructor/tree/feat/support-records)

**Comment by k94ll13nn3** [comment]
Hi, the point of this library was to bring to classes some features that could be found in records, especially the primary constructor. I don't think there is much to gain by auto generating constructor on records instead of just using the primary constructor feature. So to be fair, I'm not really sure this library is that needed for records, even if the code change is small, it is still almost double the cases to take into account, for a small benefit.
